name: Merge openwrt into Subdirectory

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  merge_openwrt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: IamRPDev/mt6000_build
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all history for accurate merging

      - name: Install git-filter-repo
        run: |
          sudo apt update
          sudo apt install -y git-filter-repo

      - name: Set up Git
        run: |
          git config --global user.name "IamRPDev"
          git config --global user.email "dev@netlogin.xyz"

      - name: Add and Fetch openwrt Repository
        run: |
          git remote add openwrt https://github.com/openwrt/openwrt.git
          git fetch openwrt main
          git checkout -b openwrt-branch openwrt/main
          git filter-repo --to-subdirectory-filter openwrt
          git checkout main
          git merge --allow-unrelated-histories openwrt-branch -m "Merge openwrt into openwrt subdirectory"

      - name: Push Merged Content to Target Repository
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
